### PR TITLE
Parse S3 notification

### PR DESCRIPTION
**Pull request by mrandi**
Parse also S3 notification.

Scenario:
For different accounts cloudtrail is configured to push the logs in a S3 bucket in **one** account.
To simplify the configuration, we can now leave the sns field blank in cloudtrail and use the S3 bucket notification (one place configuration).

aws-cloudtrail-processing-library can now run in this main account that contains all logs and receive notification for all accounts.

### CODE REVIEW

**Comment by curtca** [comment]
Hi mrandi, 

Thanks for the feedback and contribution. You are absolutely correct, we could use S3 notification instead of SNS. We will look at your proposed changes and merge as appropriate.

Thanks,

Curt
CloudTrail

**Comment by mrandi** [comment]
Hi, any update here? we would like to use the aws-cloudtrail-processing-library instead of a custom one.

**Comment by LappleApple** [comment]
@curtca Hi there. @mrandi and I would really appreciate an update on this PR. Thanks!

**Comment by curtca** [comment]
Hi, I don't have any update on this. We've been focusing on higher things that seem to be higher priority. Could you perhaps shed some light on what the problem is with using SNS notifications from CloudTrail instead of from S3?

**Comment by mrandi** [comment]
Hi @curtca,

the main problem is getting notification for Cloudtrail Logs from different accounts.
Pushing all logs in a single S3 bucket and configure S3 Notfication is much easier than subscribe in every account to SNS.

In both cases the notification is only a link to the file in the S3 bucket. So is basically the same, but the notification format differ a little.

Would be nice to avoid building our own version because of this small changes, and maintain it.

Are there plans to continue the developing of this project, or is consider stable and nothing will change here? (I see that the [SUPPORTED_EVENT_VERSION](https://github.com/aws/aws-cloudtrail-processing-library/blob/3aa119cc6425360f76cb96fb5c7f103db1c92ca8/src/main/java/com/amazonaws/services/cloudtrail/processinglibrary/serializer/AbstractEventSerializer.java#L49) is also not very up to date.)

Thanks!

**Comment by LappleApple** [comment]
Hi @curtca, any word on @mrandi's question/request?

**Comment by LappleApple** [comment]
Hi again :) -- the PR now has conflicts, and @mrandi is on a different project now. Wondering if we should abandon this, @curtca?

**Comment by harti2006** [comment]
Conflicts resolved. I would be happy to discuss the changes and offer my support to get them merged to upstream.

**Comment by simongjh** [comment]
Thanks for your contribution to the library! We are planning to add the S3 notification support in our upcoming releases, not too soon, you should see the updates. Thanks again!

**Comment by curtca** [comment]
Version 1.1.0 now supports parsing S3 event notifications. Check it out.

**Comment by mrandi** [comment]
@harti2006 I will than close the PR.

**Pull request closed without merging**
